FROM ubuntu:latest
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg python3 python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
CMD ["python3", "./app.py"]